version: 2

models:
  - name: stg_orders
    description: "Cleaned orders data from Olist"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: order_status
        description: "Status of the order"
        tests:
          - not_null


  - name: stg_customers
    description: "Cleaned customers data from Olist"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null

  - name: stg_order_items
    description: "Cleaned order items data"
    columns:
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
      - name: product_id
        description: "Product identifier"
        tests:
          - not_null

  - name: stg_order_payments
    description: "Cleaned payments data"
    columns:
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null

  - name: stg_sellers
    description: "Cleaned sellers data"
    columns:
      - name: seller_id
        description: "Unique seller identifier"
        tests:
          - unique
          - not_null

  - name: stg_products
    description: "Cleaned products data"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null

  - name: stg_order_reviews
    description: "Cleaned order reviews data from Olist"
    columns:
      - name: review_id
        description: "Unique review identifier"
        tests:
          - not_null
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null


